#! /bin/sh
if [ -f /usr/bin/libtool ]
then
  aclocal && aclocal && autoheader && automake --add-missing --copy && autoconf
  exit $?
else
  echo "Error: /usr/bin/libtool not found"
  echo "is libtool package installed?"
fi
