#! /bin/sh
if command -v libtool >/dev/null
then
  aclocal && aclocal && autoheader && automake --add-missing --copy && autoconf
  exit $?
else
  echo "Error: /usr/bin/libtool not found"
  echo "is libtool package installed?"
fi
